<?php session_start(); clearstatcache();
$profile = file_exists('profile.json') ? json_decode(file_get_contents('profile.json'), true) : ['name' => 'Nurin irdina', 'img' => 'https://i.pravatar.cc/150?u=nurin'];
$homework = file_exists('homework.json') ? json_decode(file_get_contents('homework.json'), true) : [];
$todo=0; $prog=0; $done=0; if(is_array($homework)) { foreach($homework as $h) { $s = $h['status'] ?? 'To-Do'; if($s=='To-Do') $todo++; elseif($s=='In Progress') $prog++; elseif($s=='Done') $done++; } }
$schedule = file_exists('schedule.json') ? json_decode(file_get_contents('schedule.json'), true) : [];
$my_courses = [['code' => 'CTU554', 'name' => 'VALUES AND CIVILIZATION II'], ['code' => 'IMS560', 'name' => 'ADVANCED DATABASE MANAGEMENT SYSTEM'], ['code' => 'IMS561', 'name' => 'WEB PUBLISHING'], ['code' => 'IMS564', 'name' => 'USER EXPERIENCE DESIGN'], ['code' => 'IMS565', 'name' => 'INFORMATION SYSTEM PROJECT MANAGEMENT'], ['code' => 'IMS566', 'name' => 'ADVANCED WEB DESIGN DEVELOPMENT AND CONTENT MANAGEMENT'], ['code' => 'LCC501', 'name' => 'ENGLISH FOR PROFESSIONAL CORRESPONDENCE'], ['code' => 'TIC451', 'name' => 'INTRODUCTORY ITALIAN (LEVEL II)']];
$att_l = []; $att_d = []; foreach($my_courses as &$c) { $f = false; foreach($schedule as $s) { if(stripos($s['task'], $c['code']) !== false) { $c['time'] = ($s['start_time'] ?? 'TBA') . " - " . ($s['end_time'] ?? 'TBA'); $history = $s['attendance_history'] ?? []; $c['att'] = count(array_filter($history, function($v){ return $v == 'p'; })); $f = true; break; } } if(!$f) { $c['time']="TBA"; $c['att']=0; } $att_l[] = $c['code']; $att_d[] = $c['att']; } ?>
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Dashboard | SproutPlan</title><link rel="stylesheet" href="css/style.css"><script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<style>html, body { margin: 0; padding: 0; height: 100vh; width: 100vw; overflow: hidden !important; background: #fdf6e9; font-family: 'Outfit', sans-serif; } .app-container { display: grid !important; grid-template-columns: 200px 1fr 280px !important; width: 100vw; height: 100vh; } .sidebar { background: #111 !important; padding: 50px 15px 20px 15px !important; display: flex !important; flex-direction: column !important; align-items: center !important; height: 100vh !important; width: 200px !important; box-sizing: border-box !important; } .user-profile { text-align: center !important; margin-bottom: 20px !important; width: 100%; } .user-profile img { width: 110px !important; height: 110px !important; border-radius: 25px !important; object-fit: cover; border: 3px solid #333; margin-bottom: 8px; } .user-name { font-size: 1.05rem !important; font-weight: 700; color: white !important; display: block; margin: 0; } .nav-link { color: #888; text-decoration: none; padding: 10px 15px; border-radius: 12px; margin-bottom: 4px; font-size: 13px; display: flex; align-items: center; gap: 10px; width: 100%; box-sizing: border-box; } .nav-link.active { background: #222; color: white; } .logout-btn { color: #ff7eb3 !important; margin-top: 5px !important; } .main-area { padding: 15px 20px !important; display: flex !important; flex-direction: column !important; height: 100vh; gap: 10px; overflow: hidden !important; box-sizing: border-box; } .card { background: white; border-radius: 20px; padding: 12px; border: 1px solid #eee; display: flex; flex-direction: column; min-height: 0; } .course-grid { display: grid !important; grid-template-columns: repeat(4, 1fr) !important; gap: 8px; } .course-item { background: #fff; padding: 8px; border-radius: 15px; border: 1px solid #eee; } .course-item b { font-size: 8px; color: var(--accent); } .course-item span { font-size: 8.5px; font-weight: 700; display: block; line-height: 1.1; margin: 2px 0; } .course-item small { font-size: 7.5px; color: #888; } .chart-container { display: grid !important; grid-template-columns: 1fr 1fr !important; gap: 10px; flex: 1; min-height: 0; } .right-panel { background: white; border-left: 1px solid #eee; padding: 15px; box-sizing: border-box; display: flex; flex-direction: column; width: 280px; height: 100vh; } .cal-row { display: grid; grid-template-columns: repeat(7, 1fr); gap: 1px; text-align: center; font-size: 10px; } .cal-day { height: 20px; display: flex; align-items: center; justify-content: center; }</style>
</head><meta name="viewport" content="width=device-width, initial-scale=1.0">
<body>
<div class="app-container">
    <aside class="sidebar"><div class="user-profile"><img src="<?= $profile['img'] ?>" alt="Profile" id="profileImage"><span class="user-name"><?= $profile['name'] ?></span><label for="file-upload" style="color:var(--accent); cursor:pointer; font-size:9px; font-weight:bold; margin-top:3px; display:block;">EDIT PROFILE</label><input id="file-upload" type="file" accept="image/*" style="display:none;"></div><nav style="width: 100%;"><a href="dashboard.php" class="nav-link active">🏠 Dashboard</a><a href="schedule.php" class="nav-link">📅 Schedule</a><a href="homework.php" class="nav-link">📖 Homework</a><a href="logout.php" class="nav-link logout-btn">🚪 Logout</a></nav></aside>
    <main class="main-area">
        <header style="display:flex; justify-content:space-between; align-items:center;"><h2 style="margin:0; font-size: 20px;">Hi, <?= $profile['name'] ?> 👋</h2></header>
        <div style="height:auto;"><h4 style="margin:0 0 8px 0; font-size: 12px;">My Courses 📚</h4><div class="course-grid"><?php foreach(array_slice($my_courses, 0, 8) as $c): ?><div class="course-item"><b><?= $c['code'] ?></b><span><?= $c['name'] ?></span><small>🕒 <?= $c['time'] ?></small></div><?php endforeach; ?></div></div>
        <div class="chart-container"><div class="card"><h4 style="margin:0 0 5px 0; font-size: 12px;">Attendance Stats</h4><div style="flex:1; min-height:0;"><canvas id="attChart"></canvas></div></div><div class="card"><h4 style="margin:0 0 5px 0; font-size: 12px;">Task Overview</h4><div style="flex:1; min-height:0;"><canvas id="pieChart"></canvas></div></div></div>
    </main>
    <aside class="right-panel"><h4 style="margin:0 0 10px 0; font-size: 12px;">May 2026</h4><div class="cal-row"><?php for($i=1;$i<=31;$i++): ?><div class="cal-day"><span style="<?=($i==23)?'background:var(--accent); color:white; border-radius:50%; width:18px; height:18px; display:flex; align-items:center; justify-content:center;':''?>"><?=$i?></span></div><?php endfor; ?></div><h4 style="margin:15px 0 8px 0; font-size: 12px;">Upcoming 📖</h4><div style="flex-grow:1; overflow-y:auto; padding-right: 5px;"><?php usort($homework, function($a, $b) { return strtotime($a['due_date']) - strtotime($b['due_date']); }); $upcoming = array_filter($homework, function($h) { return $h['status'] !== 'Done'; }); foreach(array_slice($upcoming, 0, 10) as $h): ?><div style="padding:10px; border-radius:12px; background:#fdf6e9; border:1px solid #eee; border-left:4px solid <?=($h['status']=='In Progress')?'#8b5cf6':'#ff7eb3'?>; margin-bottom:8px;"><b style="font-size:10px; display:block;"><?=$h['task']?></b><small style="font-size:9px; color:#888;"><?=$h['status']?> | <?=date("d M", strtotime($h['due_date']))?></small></div><?php endforeach; ?></div></aside>
</div>
<script>
    const imgInput = document.getElementById('file-upload'); const profileImg = document.getElementById('profileImage'); if(localStorage.getItem('userProfileImg')) profileImg.src = localStorage.getItem('userProfileImg'); imgInput.addEventListener('change', function() { const reader = new FileReader(); reader.onload = function(e) { profileImg.src = e.target.result; localStorage.setItem('userProfileImg', e.target.result); }; reader.readAsDataURL(this.files[0]); });
    const txt = '#1a1a1a'; new Chart(document.getElementById('attChart'), { type:'bar', data:{ labels:<?= json_encode($att_l) ?>, datasets:[{ data:<?= json_encode($att_d) ?>, backgroundColor:'#8b5cf6', borderRadius:4 }]}, options:{ maintainAspectRatio:false, plugins:{legend:{display:false}}, scales:{ y:{max:14, ticks:{color:txt, font:{size:8}}}, x:{ticks:{color:txt, font:{size:7}}} }}}); new Chart(document.getElementById('pieChart'), { type:'pie', data:{ labels:['To-Do','In Progress','Done'], datasets:[{ data:[<?=$todo?>,<?=$prog?>,<?=$done?>], backgroundColor:['#f3f4f6','#e0e7ff','#f0fff4'], borderWidth:0 }]}, options:{ maintainAspectRatio:false, plugins:{legend:{position:'bottom', labels:{color:txt, font:{size:9}, boxWidth:10}}} }});
</script>
</body>
</html>