<?php session_start(); $hw = file_exists('homework.json') ? json_decode(file_get_contents('homework.json'), true) : []; $profile = file_exists('profile.json') ? json_decode(file_get_contents('profile.json'), true) : ['name' => 'Nurin', 'img' => 'https://i.pravatar.cc/150?u=nurin'];if(isset($_POST['add'])){ $hw[] = ['id' => uniqid(), 'task' => $_POST['task'], 'due_date' => $_POST['due_date'], 'status' => 'To-Do', 'modified' => date("d M, H:i")]; file_put_contents('homework.json', json_encode($hw)); header("Location: homework.php"); exit(); }if(isset($_POST['update_status'])){ foreach($hw as &$h){ if($h['id'] == $_POST['id']){ $h['status'] = $_POST['status']; $h['modified'] = date("d M, H:i"); break; } } file_put_contents('homework.json', json_encode($hw)); header("Location: homework.php"); exit(); }if(isset($_GET['delete'])){ $hw = array_filter($hw, function($h) { return $h['id'] !== $_GET['delete']; }); file_put_contents('homework.json', json_encode(array_values($hw))); header("Location: homework.php"); exit(); }?>
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Homework | SproutPlan</title><link rel="stylesheet" href="css/style.css">
<style>body { margin: 0; overflow: hidden; background: #fdf6e9; font-family: 'Outfit', sans-serif; } .app-container { display: grid !important; grid-template-columns: 200px 1fr !important; width: 100vw; height: 100vh; } .sidebar { background: #111 !important; padding: 50px 15px 20px 15px !important; display: flex !important; flex-direction: column !important; align-items: center !important; height: 100vh !important; width: 200px !important; box-sizing: border-box !important; } .user-profile { text-align: center !important; margin-bottom: 20px !important; width: 100%; } .user-profile img { width: 110px !important; height: 110px !important; border-radius: 25px !important; object-fit: cover; border: 3px solid #333; margin-bottom: 8px; } .user-name { font-size: 1.05rem !important; font-weight: 700; color: white !important; display: block; margin: 0; } .nav-link { color: #888; text-decoration: none; padding: 10px 15px; border-radius: 12px; margin-bottom: 4px; font-size: 13px; display: flex; align-items: center; gap: 10px; width: 100%; box-sizing: border-box; } .nav-link.active { background: #222; color: white; } .logout-btn { color: #ff7eb3 !important; margin-top: 5px !important; } .main-area { padding: 25px !important; display: flex; flex-direction: column; height: 100vh; gap: 15px; overflow-y: auto !important; box-sizing: border-box;} .grid-row { display: grid; grid-template-columns: 1fr 240px 140px; gap: 12px; align-items: center; margin-bottom: 10px; } .input-box { padding: 12px 18px !important; border-radius: 15px !important; border: 1px solid #eee !important; background: white !important; color: #1a1a1a !important; width: 100%; box-sizing: border-box; font-family: 'Outfit', sans-serif; font-size: 14px; } .add-btn { background: #000 !important; color: #fff !important; border-radius: 15px !important; padding: 12px !important; border: none !important; cursor: pointer; font-weight: 700; font-size: 14px; transition: 0.3s; } .filter-btn { padding: 10px !important; border-radius: 12px !important; border: 1px solid #eee !important; background: white; color: #1a1a1a; cursor: pointer; flex: 1; font-size: 12px; font-weight: 700; transition: 0.3s; } .filter-btn.active { background: #111 !important; color: white !important; border-color: #111 !important; } .card { background: white; border-radius: 25px; padding: 20px; border: 1px solid #eee; } .homework-table { width: 100%; border-collapse: collapse; } .homework-table td { padding: 15px 10px; border-bottom: 1px solid #eee; } .status-pill { border-radius: 10px; border: none; padding: 6px 12px; font-weight: 700; font-family: 'Outfit'; }</style>
</head><meta name="viewport" content="width=device-width, initial-scale=1.0">
<body>
<div class="app-container">
    <aside class="sidebar">
        <div class="user-profile">
            <img src="<?= $profile['img'] ?>" alt="Profile" id="profileImage">
            <span class="user-name"><?= $profile['name'] ?></span>
            <label for="file-upload" style="color:var(--accent); cursor:pointer; font-size:10px; font-weight:bold; margin-top:5px; display:block;">EDIT PROFILE</label>
            <input id="file-upload" type="file" accept="image/*" style="display:none;">
        </div>
        <nav style="width: 100%;"><a href="dashboard.php" class="nav-link">🏠 Dashboard</a><a href="schedule.php" class="nav-link">📅 Schedule</a><a href="homework.php" class="nav-link active">📖 Homework</a><a href="logout.php" class="nav-link logout-btn">🚪 Logout</a></nav>
    </aside>
    <main class="main-area">
        <header style="display:flex; justify-content:space-between; align-items:center;"><h2 style="margin:0; font-size: 24px;">Homework List ✅</h2></header>
        <form method="POST" class="grid-row"><input type="text" name="task" class="input-box" placeholder="New assignment..." required><input type="date" name="due_date" class="input-box" required><button type="submit" name="add" class="add-btn">Add Task</button></form>
        <div class="grid-row">
            <input type="text" id="taskSearch" class="input-box" placeholder="Search tasks..." onkeyup="runFilters()">
            <div style="display:flex; gap:8px; flex:1;"><button class="filter-btn active" data-filter="All" onclick="setFilter(this)">All</button><button class="filter-btn" data-filter="To-Do" onclick="setFilter(this)">To-Do</button><button class="filter-btn" data-filter="In Progress" onclick="setFilter(this)">In Progress</button><button class="filter-btn" data-filter="Done" onclick="setFilter(this)">Done</button></div>
        </div>
        <div class="card" style="padding:15px !important;">
            <table class="homework-table">
                <thead><tr style="text-align:left; color: #888; font-size: 12px; border-bottom: 2px solid #eee;"><th style="padding: 10px;">Task</th><th style="padding: 10px;">Due Date</th><th style="padding: 10px;">Status</th><th style="padding: 10px;">Last Modified</th><th style="padding: 10px;">Action</th></tr></thead>
                <tbody id="hwBody">
                    <?php foreach($hw as $h): ?><tr class="hw-row" data-status="<?= $h['status'] ?>"><td style="font-size:14px;"><b><?= htmlspecialchars($h['task']) ?></b></td><td style="font-size:13px;"><?= date("d M Y", strtotime($h['due_date'])) ?></td><td><form method="POST"><input type="hidden" name="id" value="<?= $h['id'] ?>"><input type="hidden" name="update_status" value="1"><select name="status" onchange="this.form.submit()" class="status-pill"><option value="To-Do" <?= $h['status']=='To-Do'?'selected':'' ?>>To-Do</option><option value="In Progress" <?= $h['status']=='In Progress'?'selected':'' ?>>In Progress</option><option value="Done" <?= $h['status']=='Done'?'selected':'' ?>>Done</option></select></form></td><td style="font-size:12px; color:#888;"><?= $h['modified'] ?></td><td><a href="homework.php?delete=<?= $h['id'] ?>" style="color:#ff4d4d; text-decoration:none; font-weight:bold; font-size: 18px;">&times;</a></td></tr><?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </main>
</div>
<script>
    const imgInput = document.getElementById('file-upload'); const profileImg = document.getElementById('profileImage'); if(localStorage.getItem('userProfileImg')) profileImg.src = localStorage.getItem('userProfileImg'); imgInput.addEventListener('change', function() { const reader = new FileReader(); reader.onload = function(e) { profileImg.src = e.target.result; localStorage.setItem('userProfileImg', e.target.result); }; reader.readAsDataURL(this.files[0]); });
    let currentFilter = 'All'; function setFilter(btn) { document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active')); btn.classList.add('active'); currentFilter = btn.getAttribute('data-filter'); runFilters(); } function runFilters() { const searchText = document.getElementById('taskSearch').value.toLowerCase(); const rows = document.querySelectorAll('.hw-row'); rows.forEach(row => { const taskName = row.querySelector('td b').innerText.toLowerCase(); const status = row.getAttribute('data-status'); const matchesSearch = taskName.includes(searchText); const matchesFilter = (currentFilter === 'All' || status === currentFilter); row.style.display = (matchesSearch && matchesFilter) ? '' : 'none'; }); }
</script>
</body>
</html>
</body>
</html>